name = "puter-claude-docs"
compatibility_date = "2024-01-15"

[env.production]
name = "puter-claude-docs"

[env.staging]
name = "puter-claude-docs-staging"

# Pages configuration
pages_build_output_dir = "dist"
